<h3><?= esc($user['name']) ?></h3>
<a href="#?function=index"       data-fw>Přehled</a>
<a href="#?function=form_test"   data-fw>Testovací formulář</a>
<a href="#?function=sync"        data-fw>Sync mezi okny</a>
<a href="#?function=progress"    data-fw>Progress bar</a>
<a href="#?function=busy"        data-fw>Zaneprázdněno</a>
<a href="#?function=page_about"  data-fw>O aplikaci</a>
<a href="#?function=page_time"   data-fw>Čas serveru</a>
<a href="#?function=boom"        data-fw>Vyvolat chybu 500</a>
<a href="#?function=do_logout"   data-fw>Odhlásit</a>
