<li class="nav-header">NABÍDKA</li>
<li class="nav-item">
    <a href="#?function=index" data-fw class="nav-link">
        <i class="nav-icon bi bi-house"></i><p>Úvod</p></a></li>
<li class="nav-item">
    <a href="#?function=page_about" data-fw class="nav-link">
        <i class="nav-icon bi bi-info-circle"></i><p>O aplikaci</p></a></li>
<li class="nav-item">
    <a href="#?function=form_test" data-fw class="nav-link">
        <i class="nav-icon bi bi-pencil-square"></i><p>Testovací formulář</p></a></li>
<li class="nav-item">
    <a href="#?function=progress" data-fw class="nav-link">
        <i class="nav-icon bi bi-hourglass-split"></i><p>Progress bar</p></a></li>
<li class="nav-item">
    <a href="#?function=sync" data-fw class="nav-link">
        <i class="nav-icon bi bi-window-stack"></i><p>Sync mezi okny</p></a></li>
